routes/web.php
<?php

use App\Http\Controllers\CategorieController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProduitController;
use App\Models\Categorie;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/',[HomeController::class,"index"])->name('accueil');
Route::post('/add-to-cart/{id}',[HomeController::class,"addToCart"])->name('cart.add');
Route::post('/delete-cart/{id}',[HomeController::class,'destroy'])->name('cart.destroy');
Route::get('/cart/clear',[HomeController::class,'clear'])->name('cart.clear');
Route::get('/cart',[HomeController::class,"showcart"])->name('cart.show');
Route::get("catergories/search",[CategorieController::class,"search"])->name("categories.search");
Route::resource("categories",CategorieController::class);
Route::resource("produits",ProduitController::class);

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{asset('css/main.css')}}">
    <title>@yield('title','App store')</title>
</head>
<body>
    <nav>
        <ul>
            <li><a href="{{route('accueil')}}">Accueil</a></li>
            <li><a href="{{route('categories.index')}}">Gestion des categories</a></li>
            <li><a href="{{route('produits.index')}}">Gestion des produits</a></li>
        </ul>
    </nav>
    <div class="main">
        @yield('content')
    </div>
    <footer>
        &copy;OFPPT 2024
    </footer>
</body>
</html>

resources/views/layouts/user.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{asset('css/main2.css')}}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>@yield('title','App store')</title>
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-light navbar-light mb-5 justify-content-end container">
        <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link" href="{{route('accueil')}}">Accueil</a></li>
            <li class="nav-item"><a class="nav-link" href="{{route('cart.show')}}">Mon panier</a></li>
        </ul>
    </nav>
    <div class="main">
        @yield('content')
    </div>
    <footer>
        &copy;OFPPT 2024
    </footer>
</body>
</html>