routes/web.php
<?php

use App\Http\Controllers\CategorieController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProduitController;
use App\Models\Categorie;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/',[HomeController::class,"index"])->name('accueil');
Route::post('/add-to-cart/{id}',[HomeController::class,"addToCart"])->name('cart.add');
Route::post('/delete-cart/{id}',[HomeController::class,'destroy'])->name('cart.destroy');
Route::get('/cart/clear',[HomeController::class,'clear'])->name('cart.clear');
Route::get('/cart',[HomeController::class,"showcart"])->name('cart.show');
Route::get("catergories/search",[CategorieController::class,"search"])->name("categories.search");
Route::resource("categories",CategorieController::class);
Route::resource("produits",ProduitController::class);

app/Models/Produit.php
<?php

namespace App\Models;

use App\Models\Categorie;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Produit extends Model
{
    use HasFactory;
    protected $fillable =[
        'image',
        'designation',
        'prix_u',
        'quantite_stock',
        'categorie_id'
    ];
    public function categorie(){
       return  $this->belongsTo(Categorie::class);
    }
}

app/Http/Controllers/ProduitController.php
<?php

namespace App\Http\Controllers;
use App\Models\Produit;
use App\Models\Categorie;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;

class ProduitController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $categories = Categorie::all();
        $q = Produit::query();
        $des = $request->query("designation");
        $cat = $request->query('categorie_id');
        $stock = $request->query('quantite_stock');
        $prix_min = $request->query("prix_min");
        $prix_max = $request->query("prix_max");
        if($des){
            $q->where('designation','like','%'.$des.'%');
        }
        if($prix_min&&$prix_max){
            $q->whereBetween('prix_u',[$prix_min,$prix_max]);
        }
        elseif($prix_min){
            $q->where('prix_u','>',$prix_min);
        }
        elseif($prix_max){
            $q->where('prix_u','<',$prix_max);
        }
        if($cat){
            $q->where('categorie_id','like',$cat);
        }
        if($stock){
            $q->where('quantite_stock','like',0);
        }
        $produits = $q->paginate(15)->appends($request->all());
        return view("produits.index",compact('produits','categories','cat'));
    }
    public function create()
    { 
        $categories = Categorie::all();
        return view('produits.create',compact('categories'));
    }
    public function store(Request $request)
    {
        // $cat=new Categorie();
        // $cat->designation=$request->input('designation');
        // $cat->description=$request->input('description');
        // $cat->save();
        $validatedData = $request->validate([
            'designation'=>'required|unique:produits,designation',
            'prix_u'=>'required|numeric',
            'quantite_stock'=>'required|integer',
            'categorie_id'=>'required',
            'image'=>'image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);
        if($request->hasFile('image')){
            $imagePath = $request->file('image')->store('produits/images','public');
            $validatedData['image'] = $imagePath;
        }
        Produit::create($validatedData);
        return redirect()->route('produits.index');
    }
    public function edit(string $id)
    {
        $categories = Categorie::all();
        $p=Produit::find($id);
        if(is_null($p)){
            abort(404,"Resource non trouve");
        }
        return view('produits.edit',compact('p','categories'));
    }
    public function update(Request $request, string $id)
    {
        $validatedData = $request->validate([
            'designation'=>'required|unique:produits,designation',
            'prix_u'=>'required|numeric',
            'quantite_stock'=>'required|integer',
            'categorie_id'=>'required',
            'image'=>'image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);
        if($request->hasFile('image')){
            $imagePath = $request->file('image')->store('produits/images','public');
            $validatedData['image'] = $imagePath;
        }
        $p=Produit::find($id);
        $p->update($validatedData);
        return redirect()->route('produits.index');
        
    }
    public function show(int $id)
    {
        $p=Produit::find($id);
        
        return view('cart.showp')->with("p",$p);
    }
    /**
     * Show the form for creating a new resource.
     */

}

resources/views/produits/create.blade.php
@extends('layouts.admin')
 @section('title','Ajouter un produit')
 @section('content')
    <h1>Creer un nouveau produit</h1>
    <form enctype="multipart/form-data" action="{{route('produits.store')}}" method="POST">
        @csrf
        <div>
            <label for="image">Select image:</label>
            <input type="file" id="image" name="image" accept="images/*">
        </div>
        <div>
        <label for="designation">Designation</label>
        <input type="text" name="designation" id="designation">
        </div>
        <div>
        <label for="prix_u">Prix</label>
        <input type="number" name="prix_u" id="prix_u">
        </div>
        <div>
        <label for="quantite_stock">Quantite en stock</label>
        <input type="number" name="quantite_stock" id="quantite_stock">
        </div>
         <div>
         <label for="cateforie_id">Categorie</label>
        <select name="categorie_id" id="categorie_id">
            @foreach($categories as $c)
            <option value="{{$c->id}}">{{$c->designation}}</option>
            @endforeach
        </select>
        </div>
            <input type="submit" value="Ajouter">
        </div>
    </form>
    <div>
        @if($errors->any())
        <ul>
          @foreach($errors->all() as $er)
           <li>{{$er}}</li>
           
           @endforeach
        </ul>
         


        @endif
    </div>
@endsection

resources/views/produits/edit.blade.php
@extends('layouts.admin')
 @section('title','Modifier un produit')
 @section('content')

    <h1>Modifier le produit num {{$p->id}}</h1>
    <form enctype="multipart/form-data" action="{{route('produits.update',["produit"=>$p->id])}}" method="POST">
        @csrf
        @method('PUT')
        <div>
            <label for="image">Select image:</label>
            <input type="file" id="image" name="image" accept="images/*">
        </div>
        <div>
        <label for="designation">Designation</label>
        <input type="text" name="designation" id="designation" value="{{$p->designation}}">
        </div>
        <div>
        <label for="prix_u">Prix</label>
        <input type="number" name="prix_u" id="prix_u" value="{{$p->prix_u}}">
        </div>
        <div>
        <label for="quantite_stock">Quantite en stock</label>
        <input type="number" name="quantite_stock" id="quantite_stock" value="{{$p->quantite_stock}}">
        </div>
         <div>
         <label for="cateforie_id">Categorie</label>
        <select name="categorie_id" id="categorie_id">
            @foreach($categories as $c)
            @if($c->id == $p->categorie->id)
            <option selected="selected" value="{{$c->id}}">{{$c->designation}}</option>
            @else
            <option value="{{$c->id}}">{{$c->designation}}</option>
            @endif
            @endforeach
        </select>
        <div>
            <input type="submit" value="Modifier">
        </div>
    </form>
    <div>
        @if($errors->any())
        <ul>
          @foreach($errors->all() as $er)
           <li>{{$er}}</li>
           
           @endforeach
        </ul>
         


        @endif
    </div>

@endsection

resources/views/produits/index.blade.php
@extends('layouts.admin')
 @section('title','Gestion des Produits')
 @section('content')
     
    <h1>Liste des Produits</h1>
    <a class="btn btn-primary"href="{{route('produits.create')}}">Ajouter un nouveau produit</a>
    <div class="search container">
      <form action="{{route('produits.index')}}" method="GET">
        <div class="form-group">
        <label for="designation">Designation </label>
      <input type="text" class="form-control" placeholder="Designation" name="designation" id ="designation">
        </div>
        <div class="form-group">
      <label for="prix_min">Prix</label>
      <div class="minmax">
      <input type="number" class="form-control" placeholder="prix min" name="prix_min" id ="prix_min">
      <input type="number" class="form-control" placeholder="prix max" name="prix_max" id ="prix_max">
      </div>    
    </div>
        <div class="form-group">
      <select class="form-control" name="categorie_id" id="categorie_id">
        <option disabled selected value>Selectioner une categorie </option>
        @foreach($categories as $c)
        @if($c->id == $cat)
        <option selected="selected" value="{{$c->id}}">{{$c->designation}}</option>
        @else
        <option value="{{$c->id}}">{{$c->designation}}</option>
        @endif
        @endforeach
      </select>
      <div class="stock form-check">
        <label class="form-check-label" for="quatite_stock">Produits en rupture de stock</label>
        <input class="form-check-input" type="checkbox" id="quantite_stock" name="quantite_stock" value="1">
      </div>
    </div>
    <div class="sa">
      <input type="submit" class="btn btn-primary" value="rechercher">
      <a class="btn btn-success"href="{{route('produits.index',compact('produits'))}}">Afficher tout</a>
    </div> 
    </form>
      </div>
    <table id="tbl">
      <tr>
          <th>Id</th>
        <th>Designation</th>
        <th>Prix_u</th>
        <th>Quantite_stock</th>
        <th>Categorie</th>
        <th colspan="3">Actions</th>
      </tr>
      @foreach ($produits as $p)
          <tr>
            <td>{{$p->id}}</td>
            <td>{{$p->designation}}</td>
            <td>{{$p->prix_u}}</td>
            <td>{{$p->quantite_stock}}</td>
            <td>{{$p->categorie->designation}}</td>
            <td><a class="btn btn-info" href="{{route('produits.show',["produit"=>$p->id])}}">Details</a></td>
            <td><a class="btn btn-info" href="{{route('produits.edit',["produit"=>$p->id])}}">Modifier</a></td>
            <td>
                <form action="{{route('produits.destroy',["produit"=>$p->id])}}" method="POST">
                    @method('DELETE')
                    @csrf
                    <input class="btn btn-danger" type="submit" value="Supprimer" onclick="return confirm('voulez-vous supprimer cette categorie?')">
                </form></td>
          </tr>
      @endforeach
    </table>
    <div class="paginator">
      {!! $produits->links() !!}
  </div>
 @endsection

resources/views/produits/show.blade.php
@extends('layouts.admin')
 @section('title','Detail d \'un produit')
 @section('content')
    <a href="{{route('produits.index')}}">Retourner vers la liste des produits</a>
    <h1>Detail de la produi Num {{$p->id}}</h1>
    <div>
        <p><strong>Designation:</strong> {{$p->designation}}</p>
        <p><strong>prix unitair:</strong> {{$p->prix_u}}</p>
        <p><strong>Quantite en stock:</strong> {{$p->quantite_stock}}</p>
        <p><strong>Categorie:</strong> {{$p->categorie->designation}}</p>
    </div>
@endsection